### ISSUE TITLE
Move button next to Run button -- style like other "Add to Dashboard" buttons

### ISSUE THREAD

**Issue by tdheath6688** [bryan-at-looker/project_yoshi#2]
Current "Add SQL to Dashboard" button is on top menu bar. Would be better if the button were moved down next to the purple "Run" button and styled like the other Looker buttons (grey background). Button should appear to the left of the purple "Run". It should also read "Add to Dashboard", rather than "Add SQL to Dashboard".

Update the name and styling of the button to match the rest of the app. Screenshots below.

Current:
![image](https://user-images.githubusercontent.com/25750742/45371911-81b02680-b5a0-11e8-8fac-a2db3cafd82a.png)

Desired:
![image](https://user-images.githubusercontent.com/25750742/45372774-a73e2f80-b5a2-11e8-8994-e562d3063f36.png)

**Comment by tdheath6688** [comment]
@bryan-at-looker

**Comment by bryan-at-looker** [comment]
That's a much better place to put it, I'll see what I can do

**Comment by bryan-at-looker** [comment]
I was able to move it, closer, but the direct path to where that is isn't as easy I'd hoped. Also, when it was moved, the modal css changed, will need to investigate why and correct.

**Comment by bheltzel** [comment]
Completed in https://github.com/bryan-at-looker/project_yoshi/pull/7
